management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

server:
  port: 8080

routes:
  url:
    users: ${USERS_SERVICE_URL}
    core: ${CORE_SERVICE_URL}
    messaging: ${MESSAGING_SERVICE_URL}