version: "3.9"

services:

  # ---------------- DATABASES ----------------

  users-db:
    image: postgres:15
    container_name: users-db
    environment:
      POSTGRES_DB: fdmatch_users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  core-db:
    image: postgres:15
    container_name: core-db
    environment:
      POSTGRES_DB: fdmatch_core
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  # ---------- KAFKA ----------

  kafka:
    image: confluentinc/cp-kafka:7.9.0
    container_name: kafka
    environment:
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: "1"
      CLUSTER_ID: "kafka-cluster-1"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: "PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # ---------------- MICROSERVICES ----------------

  gateway:
    build: ./services/gateway
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: uat
    depends_on:
      users:
        condition: service_healthy
      core:
        condition: service_started
      kafka:
        condition: service_healthy

  users:
    build:
      context: .
      dockerfile: services/users/Dockerfile
    container_name: users
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_PROFILES_ACTIVE: uat
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
      JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
      SERVICE_API_KEY: ${SERVICE_API_KEY}
      ACCESS_EXPIRATION: ${ACCESS_EXPIRATION}
      REFRESH_EXPIRATION_DAYS: ${REFRESH_EXPIRATION_DAYS}
    depends_on:
      users-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  core:
    build:
      context: .
      dockerfile: services/core/Dockerfile
    container_name: core
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_PROFILES_ACTIVE: uat
      SERVICE_API_KEY: ${SERVICE_API_KEY}
    depends_on:
      core-db:
        condition: service_healthy
      users:
        condition: service_healthy
      kafka:
        condition: service_healthy
