version: "3.9"

services:

  # ---------------- DATABASES ----------------

  users-db:
    image: postgres:15
    container_name: users-db
    environment:
      POSTGRES_DB: fdmatch_users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  core-db:
    image: postgres:15
    container_name: core-db
    environment:
      POSTGRES_DB: fdmatch_core
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  # ---------- KAFKA ----------

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: "1"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
    ports:
      - "9092:9092"
      - "9093:9093"

  # ---------------- MICROSERVICES ----------------

  gateway:
    build: ./services/gateway
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: uat
    depends_on:
      users:
        condition: service_started
      core:
        condition: service_started
      kafka:
        condition: service_started

  users:
    build:
      context: .
      dockerfile: services/users/Dockerfile
    container_name: users
    environment:
      SPRING_PROFILES_ACTIVE: uat
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
      JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
      SERVICE_API_KEY: ${SERVICE_API_KEY}
    depends_on:
      users-db:
        condition: service_healthy

  core:
    build:
      context: .
      dockerfile: services/core/Dockerfile
    container_name: core
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: uat
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
      JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
      SERVICE_API_KEY: ${SERVICE_API_KEY}
    depends_on:
      core-db:
        condition: service_healthy
      users:
        condition: service_started