openapi: 3.0.3
info:
  title: core service api
  version: 1.3.0
  description: API для core‑модуля

paths:

  # -------------------------
  # USER
  # -------------------------

  /core/user/profile:
    post:
      description: Получение профиля пользователя (полного или публичного)
      tags:
        - user
      security:
        - bearerAuth: []
      parameters:
        - $ref: './definitions.yaml#/components/parameters/TokenHeader'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './definitions.yaml#/components/schemas/UserProfileRequest'
      responses:
        '200':
          description: Профиль пользователя
          content:
            application/json:
              schema:
                $ref: './definitions.yaml#/components/schemas/UserProfileResponse'

  /core/user/profile/edit:
    patch:
      description: Редактирование профиля пользователя
      tags:
        - user
      security:
        - bearerAuth: []
      parameters:
        - $ref: './definitions.yaml#/components/parameters/TokenHeader'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './definitions.yaml#/components/schemas/EditUserProfileRequest'
      responses:
        '200':
          description: Обновлённый профиль пользователя
          content:
            application/json:
              schema:
                $ref: './definitions.yaml#/components/schemas/EditUserProfileResponse'

  /core/user/preferences:
    get:
      description: Получение настроек пользователя (уведомления, скрытие постов)
      tags:
        - user
      security:
        - bearerAuth: []
      parameters:
        - $ref: './definitions.yaml#/components/parameters/TokenHeader'
      responses:
        '200':
          description: Настройки пользователя
          content:
            application/json:
              schema:
                $ref: './definitions.yaml#/components/schemas/UserPreferencesResponse'
    patch:
      description: Обновление настроек пользователя
      tags:
        - user
      security:
        - bearerAuth: []
      parameters:
        - $ref: './definitions.yaml#/components/parameters/TokenHeader'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './definitions.yaml#/components/schemas/UpdateUserPreferencesRequest'
      responses:
        '200':
          description: Обновлённые настройки пользователя
          content:
            application/json:
              schema:
                $ref: './definitions.yaml#/components/schemas/UserPreferencesResponse'

  /core/user/profile/friends:
    post:
      description: Получение списка друзей пользователя
      tags:
        - user
      security:
        - bearerAuth: [ ]
      parameters:
        - $ref: './definitions.yaml#/components/parameters/TokenHeader'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './definitions.yaml#/components/schemas/GetRelatedUsersRequest'
      responses:
        '200':
          description: Список друзей пользователя
          content:
            application/json:
              schema:
                $ref: './definitions.yaml#/components/schemas/FriendsResponse'

  /core/user/profile/pending_requests:
    post:
      description: получение списка заявок пользователя
      tags:
        - user
      security:
        - bearerAuth: [ ]
      parameters:
        - $ref: './definitions.yaml#/components/parameters/TokenHeader'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './definitions.yaml#/components/schemas/GetRelatedUsersRequest'
      responses:
        '200':
          description: Список заявок на лайки для пользователя
          content:
            application/json:
              schema:
                $ref: './definitions.yaml#/components/schemas/PendingRequestsResponse'


  # -------------------------
  # MATCHING
  # -------------------------

  /core/match/next:
    post:
      description: Получение списка кандидатов (pending + новые)
      tags:
        - match
      security:
        - bearerAuth: []
      parameters:
        - $ref: './definitions.yaml#/components/parameters/TokenHeader'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './definitions.yaml#/components/schemas/MatchBatchRequest'
      responses:
        '200':
          description: Список кандидатов
          content:
            application/json:
              schema:
                $ref: './definitions.yaml#/components/schemas/MatchCandidateBatchResponse'

  /core/match/react:
    post:
      description: Реакция на пользователя (лайк/дизлайк)
      tags:
        - match
      security:
        - bearerAuth: []
      parameters:
        - $ref: './definitions.yaml#/components/parameters/TokenHeader'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './definitions.yaml#/components/schemas/MatchActionRequest'
      responses:
        '200':
          description: Результат реакции
          content:
            application/json:
              schema:
                $ref: './definitions.yaml#/components/schemas/MatchActionResponse'

  /core/match/filter:
    post:
      description: Установка фильтров подбора пользователей
      tags:
        - match
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './definitions.yaml#/components/schemas/MatchFilterRequest'
      responses:
        '200':
          description: Фильтры сохранены
          content:
            application/json:
              schema:
                $ref: './definitions.yaml#/components/schemas/MatchFilterResponse'

  /core/match/get_current_filters:
    get:
      description: Установка получения текущих фильтров пользователя
      tags:
        - match
      security:
        - bearerAuth: [ ]
      responses:
        '200':
          description: Текущие фильтры
          content:
            application/json:
              schema:
                $ref: './definitions.yaml#/components/schemas/CurrentFiltersResponse'

  # -------------------------
  # POSTS
  # -------------------------

  /core/posts/get:
    post:
      description: Получение постов пользователя (с пагинацией)
      tags:
        - posts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './definitions.yaml#/components/schemas/PostsGetRequest'
      responses:
        '200':
          description: Список постов
          content:
            application/json:
              schema:
                $ref: './definitions.yaml#/components/schemas/PostListResponse'

  /core/posts/create:
    post:
      description: Создание поста
      tags:
        - posts
      security:
        - bearerAuth: []
      parameters:
        - $ref: './definitions.yaml#/components/parameters/TokenHeader'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './definitions.yaml#/components/schemas/CreatePostRequest'
      responses:
        '200':
          description: Созданный пост
          content:
            application/json:
              schema:
                $ref: './definitions.yaml#/components/schemas/CreatePostResponse'

  /core/posts/{post_id}:
    get:
      description: Получение одного поста
      tags:
        - posts
      parameters:
        - name: post_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Пост
          content:
            application/json:
              schema:
                $ref: './definitions.yaml#/components/schemas/ExtendedPostResponse'

  /core/posts/{post_id}/comments:
    post:
      description: Получение комментариев к посту
      tags:
        - posts
      parameters:
        - name: post_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './definitions.yaml#/components/schemas/CommentsGetRequest'
      responses:
        '200':
          description: Комментарии
          content:
            application/json:
              schema:
                $ref: './definitions.yaml#/components/schemas/CommentListResponse'

  /core/posts/{post_id}/like:
    post:
      description: Лайк поста
      tags:
        - posts
      security:
        - bearerAuth: []
      parameters:
        - name: post_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Лайк поставлен
          content:
            application/json:
              schema:
                $ref: './definitions.yaml#/components/schemas/PostLikeResponse'

  /core/posts/{post_id}/comment:
    post:
      description: Отправить комментарий к посту
      tags:
        - posts
      security:
        - bearerAuth: []
      parameters:
        - $ref: './definitions.yaml#/components/parameters/TokenHeader'
        - name: post_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './definitions.yaml#/components/schemas/CreateCommentRequest'
      responses:
        '200':
          description: Созданный комментарий
          content:
            application/json:
              schema:
                $ref: './definitions.yaml#/components/schemas/CreateCommentResponse'


  # -------------------------
  # FEED
  # -------------------------

  /core/feed:
    post:
      description: Лента постов мэтчей
      tags:
        - feed
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './definitions.yaml#/components/schemas/GetFeedRequest'
      responses:
        '200':
          description: Лента
          content:
            application/json:
              schema:
                $ref: './definitions.yaml#/components/schemas/PostListResponse'


  # -------------------------
  # FANDOMS
  # -------------------------

  /core/fandoms/search:
    get:
      description: Поиск фандомов по строке запроса
      tags:
        - fandom
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Список найденных фандомов
          content:
            application/json:
              schema:
                $ref: './definitions.yaml#/components/schemas/FandomListResponse'

  /core/cities/search:
    get:
      description: Поиск городов по строке запроса
      tags:
        - city
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Список найденных городов
          content:
            application/json:
              schema:
                $ref: './definitions.yaml#/components/schemas/CitySearchResponse'

  /core/fandoms/user:
    post:
      description: Получение списка фандомов пользователя
      tags:
        - fandom
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './definitions.yaml#/components/schemas/FandomsGetRequest'
      responses:
        '200':
          description: Список фандомов
          content:
            application/json:
              schema:
                $ref: './definitions.yaml#/components/schemas/FandomListResponse'


  /core/fandoms/categories:
    get:
      description: Получение списка категорий фандомов
      tags:
        - fandom
      responses:
        '200':
          description: Категории
          content:
            application/json:
              schema:
                $ref: './definitions.yaml#/components/schemas/FandomCategoryListResponse'

  /core/fandoms/request-new:
    post:
      description: Запрос на добавление нового фандома
      tags:
        - fandom
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './definitions.yaml#/components/schemas/FandomRequestCreate'
      responses:
        '200':
          description: Запрос принят
          content:
            application/json:
              schema:
                $ref: './definitions.yaml#/components/schemas/FandomRequestCreateResponse'
