server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fdmatch_core
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

clients:
  users-service:
    url: http://localhost:8081

service:
  api-key:
    some-api-key

logging:
  level:
    root: DEBUG
    org.apache.kafka: INFO
    org.apache.kafka.clients: INFO
    org.apache.kafka.clients.NetworkClient: INFO
    org.apache.kafka.clients.FetchSessionHandler: INFO
    org.springframework.kafka: INFO