server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://core-db:5432/fdmatch_core
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  privateKey: ${JWT_PRIVATE_KEY}
  publicKey: ${JWT_PUBLIC_KEY}

clients:
  users-service:
    url: http://users:8081