server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fdmatch_core
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  privateKey: ${JWT_PRIVATE_KEY}
  publicKey: ${JWT_PUBLIC_KEY}

clients:
  users-service:
    url: http://localhost:8081

service:
  api-key:
    some-api-key