package org.example.exception

enum class ErrorCode {
    USERNAME_ALREADY_EXISTS,
    EMAIL_ALREADY_EXISTS,
    INVALID_USER_DATA,
    USER_NOT_FOUND,
    USER_INACTIVE,
    USER_DELETED,
    CREDENTIALS_MISMATCH,
    CREDENTIAL_TYPE_NOT_FOUND,
    REFRESH_TOKEN_INVALID,
    VERIFICATION_CODE_INVALID,
    VERIFICATION_CODE_EXPIRED,
    INTERNAL_ERROR,
}