management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

server:
  port: 8081
  forward-headers-strategy: framework

spring:
  datasource:
    url: jdbc:postgresql://users-db:5432/fdmatch_users
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: kafka:9092

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  privateKey: ${JWT_PRIVATE_KEY}
  publicKey: ${JWT_PUBLIC_KEY}
  accessExpiration: ${ACCESS_EXPIRATION}
  refreshExpirationDays: ${REFRESH_EXPIRATION_DAYS}

clients:
  core-service:
    url: http://core:8082

service:
  api-key: ${SERVICE_API_KEY}

notifications:
  firebase:
    credentials-json: ${FIREBASE_CREDENTIALS_JSON}
    project-id: ${FIREBASE_PROJECT_ID}
