server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fdmatch_users
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

clients:
  core-service:
    url: http://localhost:8082

service:
  api-key:
    some-api-key

logging:
  level:
    org.apache.kafka: INFO
    org.apache.kafka.clients: INFO
    org.apache.kafka.clients.NetworkClient: INFO
    org.apache.kafka.clients.FetchSessionHandler: INFO
    org.springframework.kafka: INFO
    root: DEBUG

jwt:
  privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC1Ou8tBA1yZpM4Lw862p/P/k81gakX8ibEcVoJt0dHp6Jh4kVq5CzFr9KMHVFx5NcsXCrgwfC9SGLuzEFc0+tFPaVUqb7KzdtJecQWbUtSOxgS/mybPkUooQYRcgYHR1/WXSKVCRtZOZfAJS1pF1/1rehuLkH6tBUgUuANZSVValk4mhPRY3YxbyepGKZee5c7EaIXjv8l2pEUfN5MQ+CW9JVW1PK2VtNyxG3eB0/zG2qtM6q4H1JY/RnuRU7BmqukvAVkZzqFse2EpSCjZt8IBQK2okPGS4Cr9zsFLYw+yWo9gGKsw2F7kbAuS67BWRNewX0V46lS20kNwCpoZ2MbAgMBAAECggEBAI4Tf8H4tVoEVFHtgrEPB86Vfh9iYN/m9MF4Y6/OQVFJeCHos6cS7o6kQhmaOmlhj9a1AuBk6ohZoUW4V12gvYbwxxZSZMK1E77MeQ9j63Kx5TOuxhIGhU1Ov2UZ0OQP7nAtX5kbJJeUcQUvoCQNMSt3hQortYoHd7B5iDC4JMaKYL8qS/CCGeGZyUD31/QBtEevhNDmNrwx8B2azOnWOQeyMdlQQlMM/4Ma8BSiUeCRteTmcpFEov2y6V4ZjR9gPNGbWfj6dcRkHHVYdW/3/zt7V3zulgaO/NnQZ3kJKnLPpnElrR69LVDVViYgq6Vjr5nM1d5sLUh8sNmDcYvWckECgYEA5QtSh5WfGeyr5nwdUUn27bnaBWBfd8oJPcwlBTv2zy3iTswlZ4ai7YZPWlzuBLIIkaNcQb/J1BuPcJy+igfC0sL8ihIMplOiYfi8DEro+29fa8YRp7WLHHLjf/iEkFmXzEy04Dr26D+2KbaYsS/kcuCVLYK9mansGLGK6dGMdtECgYEAyo8QdrlmakLuRVFKQNx2/PzRi2TJdySbM7HXgGOGqddFq03L/yBwbgzF0c4KEHletjTcNL44UDLGoHRH8NaEREyV8DGYdcRfZzm7SOacSZB7eyzD5YOtSnVhktePvonpIfe11/H4vUmESyqaZap9629VHuC4AVip3P0v2IZQDisCgYA2RoqWCoSbNhQ+F+cynh5fkwzw/TdiQYQTGs8jAGSqD6tzFLlAYQ02z/754M+eWTnimR2BjxsaojVJcDtOpiwqmX4SkdhhiawPH0wgdZfkDS5Fcbg5T7HZWfhDGPcA5dos1Xh/MjnUK1TVaamhQ0IVXta65CJdyYBjEZ9jbP6mIQKBgHOagN/xYgUFW+1Nvp4T9Qjf1UvD4sNPrhAr0H0i0ClAhi+FQAbEYcY9He1mtRG/4xEETCUB5yvGPtw2YRSPqX89YllqRMP5piVIqp2pl8rYXdDntInZw9357g0bX5t0JAzRzgOHwtltCsbHcsTRL/pdWOw9fmauToukKFlgFnJvAoGAHevSUN60za8naAw7TMt8ipGAG/4/L2Dqy0rgLyRrHLTmJgmk1+tFPFdXzAxq/dSefxkTdDhleuYBeVQpKrSHUfDGcMlYKBEE8oxwdNrFvjENk4Rv9cQSjLrTpktZBzhzf39QKWBkeVSe6AGMKVIQ/Vuz8r6CI+X4NSqDqr5+zCs=
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtTrvLQQNcmaTOC8POtqfz/5PNYGpF/ImxHFaCbdHR6eiYeJFauQsxa/SjB1RceTXLFwq4MHwvUhi7sxBXNPrRT2lVKm+ys3bSXnEFm1LUjsYEv5smz5FKKEGEXIGB0df1l0ilQkbWTmXwCUtaRdf9a3obi5B+rQVIFLgDWUlVWpZOJoT0WN2MW8nqRimXnuXOxGiF47/JdqRFHzeTEPglvSVVtTytlbTcsRt3gdP8xtqrTOquB9SWP0Z7kVOwZqrpLwFZGc6hbHthKUgo2bfCAUCtqJDxkuAq/c7BS2MPslqPYBirMNhe5GwLkuuwVkTXsF9FeOpUttJDcAqaGdjGwIDAQAB
  accessExpiration: 900000
  refreshExpirationDays: 60