server:
  port: 8081
  forward-headers-strategy: framework

spring:
  datasource:
    url: jdbc:postgresql://users-db:5432/fdmatch_users
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  privateKey: ${JWT_PRIVATE_KEY}
  publicKey: ${JWT_PUBLIC_KEY}

clients:
  core-service:
    url: http://core:8082

service:
  api-key: {SERVICE_API_KEY}