server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fdmatch_users
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

clients:
  core-service:
    url: http://localhost:8082

service:
  api-key:
    some-api-key

jwt:
  privateKey: ${JWT_PRIVATE_KEY}
  publicKey: ${JWT_PUBLIC_KEY}