jwt:
  access-expiration: 900000 # 15 mins
  refresh-expiration-days: 60

spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/fdmatch_users
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect