jwt:
  access-expiration: 900000
  refresh-expiration-days: 60

management:
  endpoints:
    web:
      exposure:
        include: health

spring:
  jpa:
    open-in-view: false
  profiles.active: local